name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:5.5'
          - 'swift:5.6'
          - 'swift:5.7'
    
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        swift build
