name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
  pull_request:
    branches:
    - main
    paths:
    - '**.swift'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['swift:5.4-bionic', 'swift:5.4-focal', 'swift:5.4-amazonlinux2', 'swift:5.4-centos8']
    
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        swift build
