name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['nightly-5.6-bionic', 'nightly-5.6-focal', 'nightly-5.6-centos8', 'nightly-5.6-amazonlinux2']
    
    container:
      image: swiftlang/swift:${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        swift build
